---
- hosts: all
  become: true
  pre_tasks:

  - name: Install updates for Rocky
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Install updates for Ubuntu
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

   - name: install apache on web servers
     ansible.builtin.apt:
       name:
        - apache2
        - libapache2-mod-php
     when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

   - name: install mariadb package on Rocky servers
     ansible.builtin.dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "Rocky"
