- name: install apache on web servers (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
  when: ansible_distribution == "Ubuntu"

- name: ensure apache is running (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"

- name: copy html file for site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
